// Generated by CIRCT firtool-1.62.1
module Demo(
  input  clock,
         reset,
         io_enable,
  output io_out
);

  reg flip;
  always @(posedge clock) begin
    if (reset)
      flip <= 1'h0;
    else
      flip <= io_enable & ~flip;
  end // always @(posedge)
  assign io_out = flip;
endmodule

