// Generated by CIRCT firtool-1.62.1
module Mux41(
  input  [3:0] io_data,
  input  [1:0] io_key,
  output       io_out
);

  wire [3:0] _GEN = {{io_data[3]}, {io_data[2]}, {io_data[1]}, {io_data[0]}};
  assign io_out = _GEN[io_key];
endmodule

