// Generated by CIRCT firtool-1.62.1
module D_Flipflop(
  input  clock,
         reset,
         io_D,
  output io_Q
);

  reg io_Q_REG;
  always @(posedge clock) begin
    if (reset)
      io_Q_REG <= 1'h0;
    else
      io_Q_REG <= io_D;
  end // always @(posedge)
  assign io_Q = io_Q_REG;
endmodule

