// Generated by CIRCT firtool-1.62.1
module Encode42(
  input        io_en,
  input  [3:0] io_in,
  output [1:0] io_out
);

  assign io_out =
    io_en ? (io_in == 4'h8 ? 2'h3 : io_in == 4'h4 ? 2'h2 : {1'h0, io_in == 4'h2}) : 2'h0;
endmodule

